/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutFrame.java
 *
 * Created on 10-Mar-2009, 08:16:32
 */

package glug.gui;

/**
 * @author roberto
 */
public class AboutBox extends javax.swing.JDialog {

    /**
     * Creates new form AboutFrame
     */
    public AboutBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glugLabel = new javax.swing.JLabel();
        glugGlugGlugLabel = new javax.swing.JLabel();
        hicLabel = new javax.swing.JLabel();
        contributorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Glug");
        setResizable(false);

        glugLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 128));
        glugLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glugLabel.setText("Glug");

        glugGlugGlugLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 20));
        glugGlugGlugLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glugGlugGlugLabel.setText("Glug glug glug");

        hicLabel.setText("(hic)");

        contributorLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16));
        contributorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contributorLabel.setText("contributed by Roberto Tyley");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(glugLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(205, 205, 205)
                                                .addComponent(hicLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(contributorLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(glugGlugGlugLabel)))
                                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(glugLabel)
                                .addGap(12, 12, 12)
                                .addComponent(glugGlugGlugLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(contributorLabel)
                                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contributorLabel;
    private javax.swing.JLabel glugGlugGlugLabel;
    private javax.swing.JLabel glugLabel;
    private javax.swing.JLabel hicLabel;
    // End of variables declaration//GEN-END:variables

}
